### ISSUE TITLE
Force resource recreation

### ISSUE THREAD

**Issue by Clausewitz45** [arehmandev/Terraform-ASGIP#1]
Hi, and thanks for this workaround :+1: 

I'm using your workaround for my ECSs which are member of an ASG. I really like the approach, and I have only one problem (except how to update the policy regarding the ASG changes): it's just executed at the first time - the second time it's not get executed by `terraform apply` because it's already in the state. I know that there is an option to taint or remove resources from the state - but maybe you have an idea how to recreate this resource automatically everytime. 

regards,
Csaba

**Comment by arehmandev** [comment]
@Clausewitz45 Apologies mate I didnt realise this repo was being used by others lol - just merged a PR for a trigger of this process (hope you found a workaround)
